[project]
name = "react-simple"
version = "0.1.0"
description = "A simple ReAct agent code"
authors = ["royp-nrd <roy@neradot.com>"]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openai>=1.64.0",
    "python-dotenv>=1.0.1",
]
